module.exports={
    dialect:'postgres',
    host:'localhost',
    username:'postgres',
    passworld:'docker',
    database:'gobarber',
    define:{
        timestamps:true,
        underscored:true,
        underscoredAll:true,
    },
};